#!/usr/bin/env python3
"""Measure the RENDERER, not the analysis. Opt-in; NOT part of tests/run.py.

    python tests/render_bench.py clock     # is the drawn motion smooth, and by how much
    python tests/render_bench.py morph     # every shape pair's transition, all 72
    python tests/render_bench.py edges     # how rough is the silhouette, and where
    python tests/render_bench.py costs     # what each pass actually costs, by ablation
    python tests/render_bench.py filter    # what a filter cell costs the subject
    python tests/render_bench.py motion    # the guarantees viewer.html makes about turning
    python tests/render_bench.py shape     # AO and the reflection gate, asserted continuous
    python tests/render_bench.py export    # the MP4 the export path writes, parsed and decoded
    python tests/render_bench.py director  # the Director's timing rules, asserted
    python tests/render_bench.py site      # the purchase pages, in three configurations
    python tests/render_bench.py all

THE `site` ARM IS THE ODD ONE and does not touch the renderer at all. It is here rather than in
run.py for the same reason as everything else in this file: it needs Chrome. It drives the two
site pages against three servers -- a real one with Gumroad configured and only the call that
leaves the machine stubbed (tests/site_stub.py), the ordinary one with Gumroad off, and a plain
http.server with no API at all -- because the interesting failures there are about
configuration rather than about code. It starts and stops its own servers and uses a throwaway
database; it never opens out/billing.db.

WHY THIS FILE EXISTS. Every measurement in viewer.html had to be rebuilt by hand before it
could be taken, and that cost real accuracy: MORPH's constants were tuned on three shape pairs
out of seventy-two, not because three was thought sufficient but because a fourth meant more
hand-driving. The claims in that file are only as good as the ability to re-run them, and
until now there was no way to.

WHY IT DOES NOT USE A NORMAL BROWSER TAB. requestAnimationFrame is throttled to about 1fps in
a tab the OS considers hidden, and an embedded preview pane can report document.hidden === true
even while it is on screen. Measured there: 19 frames in 20 seconds. Every per-frame number
this file produces would be silently wrong. So it drives its own Chrome over CDP with
background throttling disabled, and asserts document.hidden === false before believing anything.

WHAT IT NEEDS. A server on ATONAL_PORT (default 8770) and Google Chrome. The audio fixture is
generated by tests/fixtures.py and copied into assets/ for the page to fetch, because the
server's static allowlist is deliberately narrow (see _STATIC_DIRS); it is removed again on the
way out, including on failure.

DEPENDENCIES. websocket-client, numpy, Pillow. Unlike the other two suites this one is not
dependency-free, which is the other reason it is not in run.py.
"""
import atexit
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, ROOT)

PORT = int(os.environ.get("ATONAL_PORT", "8770"))
CDP_PORT = int(os.environ.get("ATONAL_CDP_PORT", "9333"))
CHROME = os.environ.get("ATONAL_CHROME",
                        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome")


# ------------------------------------------------------------------ CDP driver
class Chrome:
    """Just enough Chrome DevTools Protocol to evaluate JS and read the answer."""

    def __init__(self, port=CDP_PORT):
        import websocket                                   # noqa: F401  (checked early)
        self.port = port
        self.dir = tempfile.mkdtemp(prefix="atonal-bench-")
        self.proc = subprocess.Popen(
            [CHROME,
             "--remote-debugging-port=%d" % port,
             "--user-data-dir=" + self.dir,
             "--no-first-run", "--no-default-browser-check",
             # WITHOUT THESE THREE THE NUMBERS ARE FICTION -- see the module docstring.
             "--disable-background-timer-throttling",
             "--disable-backgrounding-occluded-windows",
             "--disable-renderer-backgrounding",
             "--disable-features=CalculateNativeWinOcclusion",
             "--autoplay-policy=no-user-gesture-required",
             "--mute-audio", "--window-size=1280,800", "--headless=new",
             "about:blank"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        self.ws = None
        self._id = 0

    def connect(self, url, timeout=40):
        import websocket
        deadline = time.time() + timeout
        last = None
        while time.time() < deadline:
            try:
                tabs = json.load(urllib.request.urlopen(
                    "http://127.0.0.1:%d/json" % self.port, timeout=2))
                page = next((t for t in tabs if t["type"] == "page"), None)
                if page:
                    # suppress_origin: DevTools rejects a WebSocket carrying an Origin header
                    # with 403. The alternative is --remote-allow-origins=*, which is a wider
                    # hole in a debugging endpoint than simply not sending the header.
                    self.ws = websocket.create_connection(
                        page["webSocketDebuggerUrl"], max_size=256 * 1024 * 1024,
                        suppress_origin=True)
                    self.send("Page.enable")
                    self.send("Runtime.enable")
                    self.send("Page.navigate", {"url": url})
                    time.sleep(2.0)
                    return
            except Exception as e:                          # Chrome is still starting
                last = e
                time.sleep(0.4)
        raise RuntimeError("could not attach to Chrome on %d (%s)" % (self.port, last))

    def send(self, method, params=None, timeout=180):
        self._id += 1
        mid = self._id
        self.ws.send(json.dumps({"id": mid, "method": method, "params": params or {}}))
        self.ws.settimeout(timeout)
        while True:
            msg = json.loads(self.ws.recv())
            if msg.get("id") == mid:
                if "error" in msg:
                    raise RuntimeError(msg["error"])
                return msg.get("result")

    def js(self, expr, timeout=180):
        r = self.send("Runtime.evaluate",
                      {"expression": "(async()=>{ %s })()" % expr,
                       "awaitPromise": True, "returnByValue": True,
                       "timeout": timeout * 1000},
                      timeout=timeout + 20)
        if r.get("exceptionDetails"):
            raise RuntimeError(json.dumps(r["exceptionDetails"])[:600])
        return r["result"].get("value")

    def close(self):
        try:
            self.ws.close()
        except Exception:
            pass
        try:
            self.proc.terminate()
            self.proc.wait(timeout=5)
        except Exception:
            self.proc.kill()
        shutil.rmtree(self.dir, ignore_errors=True)


# ------------------------------------------------------------------ page setup
def serve_fixture():
    """Put a known track where the page can fetch it, and take it away afterwards.

    A generated fixture rather than a real file: the bar grid, the section boundaries and the
    tempo are known by construction, so a measurement can be checked against them.
    """
    import fixtures
    path, truth, bpm = fixtures.structure_track()
    dest = os.path.join(ROOT, "assets", "_bench.wav")
    shutil.copy(path, dest)
    atexit.register(lambda: os.path.exists(dest) and os.remove(dest))
    return "/assets/_bench.wav", truth, bpm


def open_viewer(query=""):
    c = Chrome()
    try:
        c.connect("http://127.0.0.1:%d/%s" % (PORT, query))
    except Exception:
        c.close()
        raise
    hidden = c.js("return document.hidden;")
    if hidden:
        c.close()
        raise RuntimeError("document.hidden is true -- rAF would be throttled; refusing to "
                           "report per-frame numbers. See the module docstring.")
    return c


def load_track(c, url, timeout=300):
    c.js("""window.SYNC={};
        const r=await fetch('%s'); const b=await r.blob();
        loadFile(new File([b],'bench.wav',{type:'audio/wav'})); return 1;""" % url)
    deadline = time.time() + timeout
    while time.time() < deadline:
        st = json.loads(c.js("return JSON.stringify({d:!!window.DIRECTOR,"
                             "p:window.SYNC&&window.SYNC.playing});"))
        if st.get("d") and st.get("p"):
            return st
        time.sleep(2)
    raise RuntimeError("track never started playing")


def pin(c):
    """Everything still but the thing under test. Comparing across page loads is void --
    TFREEZE pins the camera and section wherever they happened to be, and the same build has
    measured 0.19 and 1.27 for one quantity on two loads."""
    return c.js("""pause(); window.TFREEZE=40.0; window.QLOCK=true;
        window.POSE={spin:1.0,cam:0.6,tumble:0.4,swirl:0.2};
        await new Promise(r=>setTimeout(r,400)); return 'pinned';""")


# ------------------------------------------------------------------ clock judder
def bench_clock(c, url, secs=25):
    """How smooth is the drawn motion, in degrees and then in pixels?

    Fitted against the WALL clock, not the transport, so the answer does not depend on frame
    cadence -- which is the whole difficulty, since neither a hidden tab nor a headless one
    runs at a steady 60. A local CUBIC absorbs the bar swing, the ladder's rate ramps and any
    real acceleration, leaving only what steps at the frame scale.
    """
    import numpy as np
    load_track(c, url)
    raw = c.js("""
        window.__C=[]; window.__on=true;
        (function tick(){ if(!window.__on) return; const s=window.SYNC;
          if(s&&s.playing) window.__C.push([performance.now(), pos(), s.spin, s.spinOut,
                                            s.tumble, s.swirl, s.swirlOut||0]);
          requestAnimationFrame(tick); })();
        await new Promise(r=>setTimeout(r,%d)); window.__on=false;
        return JSON.stringify(window.__C);""" % (secs * 1000), timeout=secs + 90)
    a = np.array(json.loads(raw), dtype=np.float64)
    wall = (a[:, 0] - a[0, 0]) / 1000.0

    def judder(ang, win=0.40, deg=3):
        out, i = [], 0
        while i < len(wall):
            j = np.searchsorted(wall, wall[i] + win)
            if j - i >= deg + 5:
                w = wall[i:j] - wall[i]
                y = ang[i:j]
                out.append((y - np.polyval(np.polyfit(w, y, deg), w)) * 180.0 / np.pi)
            i = j if j > i else i + 1
        return np.concatenate(out) if out else np.array([0.0])

    print("  %d frames over %.1fs (%.1f fps)" % (len(a), wall[-1], len(a) / wall[-1]))
    # the clock itself: residual against a straight line in wall time
    y = a[:, 1] - a[0, 1]
    m, b = np.linalg.lstsq(np.vstack([wall, np.ones_like(wall)]).T, y, rcond=None)[0]
    res = (y - (m * wall + b)) * 1000.0
    d = np.diff(a[:, 1])
    d = d[d > 1e-9]
    q = np.median(d / np.round(d / 0.0053333)) * 1000.0 if len(d) else float("nan")
    print("  clock: slope %.6f (1.0 = no drift), residual rms %.2fms, ptp %.2fms, quantum ~%.3fms"
          % (m, res.std(), res.max() - res.min(), q))
    out = {}
    # swirlOut IS THE DOMINANT DRAWN ROTATION when FACE.on, which is the default: the continuous
    # turn was moved onto the plate's own normal so it cannot present the edge, and spinOut is
    # then only the bounded lean. Measuring spinOut alone would report the judder of the small
    # motion and miss the large one.
    for name, col in (("formSpin", 2), ("spinOut", 3), ("formTumble", 4), ("formSwirl", 5),
                      ("swirlOut", 6)):
        r = judder(a[:, col])
        out[name] = r.std()
        print("  %-10s judder %.4f deg rms   p95 %.4f   ptp %.4f"
              % (name, r.std(), np.percentile(np.abs(r), 95), r.max() - r.min()))
    # degrees -> pixels. u_fov is a TRUE vertical FOV (f=0.5/tan(fov/2), uv.y spans +/-0.5),
    # and a spin of alpha moves a surface point at `reach` by reach*alpha, subtending
    # reach*alpha/dist at the camera.
    g = json.loads(c.js("""const cv=document.querySelector('canvas');
        return JSON.stringify({h:cv.height, dpr:devicePixelRatio, reach:frameReach(),
                               dist:CM.dist, fov:CM.fov});"""))
    px_per_rad = (g["h"] / g["dpr"]) / (2.0 * np.arctan(0.5 / (0.5 / np.tan(g["fov"] / 2))))
    scale = (g["reach"] / g["dist"]) * px_per_rad
    print("  geometry: reach %.2f at dist %.2f, fov %.3f -> %.0f px per radian of spin"
          % (g["reach"], g["dist"], g["fov"], scale))
    # The LARGER of the two form rotations, because which one carries the turn depends on FACE:
    # spinOut when the free three-axis motion is on, swirlOut when the plate is held face-on.
    worst = max(out["spinOut"], out.get("swirlOut", 0.0))
    print("  DRAWN JUDDER %.3f px rms  (sub-pixel is the expected answer; see the note at"
          " the read point in viewer.html)" % (worst * np.pi / 180.0 * scale))
    return out


# ------------------------------------------------------------------ morph sweep
GRAB = """
window.__grab = function(){
  const cv=document.querySelector('canvas'), g=cv.getContext('webgl2');
  const W=256,H=256, x=Math.max(0,(cv.width-W*2)>>1), y=Math.max(0,(cv.height-H*2)>>1);
  const buf=new Uint8Array(W*2*H*2*4);
  g.readPixels(x,y,W*2,H*2,g.RGBA,g.UNSIGNED_BYTE,buf);
  const out=new Float32Array(W*H);
  for(let j=0;j<H;j++) for(let i=0;i<W;i++){
    const o=((j*2)*(W*2)+(i*2))*4;
    out[j*W+i]=buf[o]*0.299+buf[o+1]*0.587+buf[o+2]*0.114; }
  return out; };
window.__sweep = async function(a,b,n){
  window.PAIRPIN=[a,b]; window.MIXPIN=0;
  await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
  const d=[]; let prev=null;
  for(let i=0;i<n;i++){
    window.MIXPIN=i/(n-1);
    await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
    const f=window.__grab();
    if(prev){ let s=0; for(let k=0;k<f.length;k++) s+=Math.abs(f[k]-prev[k]); d.push(s/f.length); }
    prev=f; }
  return d; };
return 'ready';
"""


def bench_morph(c, url, modes=9, n=21):
    """Every ordered shape pair's transition, in ONE page load.

    readPixels off a centred box, not a screenshot: 1512 full-frame PNGs over CDP wedged the
    browser. `lurch` is the worst step-to-step ratio and `evenness` the rate's relative spread;
    neither can separate a lurch from deliberate easing, so they compare curves and are not
    absolute defect measures.
    """
    import numpy as np
    load_track(c, url)
    print("  " + pin(c))
    c.js(GRAB)
    nf = c.js("""const a=window.__grab();
        await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
        const b=window.__grab(); let s=0; for(let k=0;k<a.length;k++) s+=Math.abs(a[k]-b[k]);
        return s/a.length;""")
    print("  noise floor (same pose, two grabs): %.4f levels" % nf)
    res = {}
    for a in range(modes):
        for b in range(modes):
            if a == b:
                continue
            d = np.array(c.js("return await window.__sweep(%d,%d,%d);" % (a, b, n), timeout=120),
                         dtype=np.float64)
            chk = json.loads(c.js("return JSON.stringify({m:window.SYNC.mode,"
                                  "m2:window.SYNC.mode2});"))
            # PAIRPIN silently doing nothing is the failure this whole sweep once produced
            if chk["m"] != a or chk["m2"] != b:
                raise RuntimeError("PAIRPIN did not take for %d->%d: %s" % (a, b, chk))
            if d.size < 3 or d.mean() <= 1e-9:
                continue
            m = d.mean()
            rt = np.maximum(d[1:], 1e-9) / np.maximum(d[:-1], 1e-9)
            res["%d->%d" % (a, b)] = {"lurch": float(max(rt.max(), (1.0 / rt).max())),
                                      "evenness": float(d.std() / m),
                                      "start": float(d[0] / m), "end": float(d[-1] / m)}
    c.js("window.PAIRPIN=null; window.MIXPIN=null; return 1;")
    L = np.array([r["lurch"] for r in res.values()])
    E = np.array([r["evenness"] for r in res.values()])
    print("  %d pairs | lurch  median %.2f p90 %.2f min %.2f max %.2f"
          % (len(res), np.median(L), np.percentile(L, 90), L.min(), L.max()))
    print("  %d pairs | even   median %.3f p90 %.3f max %.3f"
          % (len(res), np.median(E), np.percentile(E, 90), E.max()))
    worst = sorted(res, key=lambda k: -res[k]["lurch"])[:5]
    print("  worst: " + ", ".join("%s %.2f" % (k, res[k]["lurch"]) for k in worst))
    # THE RIG CHECKING ITSELF: the curve is time-symmetric, so a->b and b->a must agree.
    dl = [abs(res[k]["lurch"] - res["%s->%s" % tuple(k.split("->")[::-1])]["lurch"])
          for k in res if "%s->%s" % tuple(k.split("->")[::-1]) in res]
    print("  symmetry check (a->b vs b->a): worst lurch disagreement %.4f" % max(dl))
    return res


# ------------------------------------------------------------------ entry
# ------------------------------------------------------------------ silhouette quality
# The default framebuffer is undefined once the frame has been presented, so a readPixels from
# Runtime.evaluate returns a cleared buffer -- measured as every arm of a sweep coming back
# byte-identical with a whole-box RMSE of exactly 0.000, which is what sent this down a blind
# alley the first time. The read has to happen in the SAME TASK as the draw. frame() reschedules
# itself at its top, so wrapping requestAnimationFrame survives, and the grab runs after frame()
# returns and before the compositor takes it.
_GRAB_HOOK = """
  const _raf=window.requestAnimationFrame.bind(window);
  window.requestAnimationFrame=cb=>_raf(t=>{ cb(t);
    if(window.__WANT){ const W=glc.width,H=glc.height;
      const x0=(W>>1)-320,y0=(H>>1)-220,w=640,h=440;
      const px=new Uint8Array(w*h*4);
      gl.bindFramebuffer(gl.FRAMEBUFFER,null);
      gl.readPixels(x0,y0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,px);
      let s=''; for(let i=0;i<w*h;i++) s+=String.fromCharCode(px[i*4]);
      window.__GOT={w:w,h:h,r:btoa(s)}; window.__WANT=false; } });
  return 1;
"""
_GRAB = """
  window.QLOCK=true; rscale=%f; DX.sharpen=%f; applyScale();
  await new Promise(r=>setTimeout(r,700));
  window.__GOT=null; window.__WANT=true;
  for(let i=0;i<300 && !window.__GOT;i++) await new Promise(r=>setTimeout(r,20));
  return JSON.stringify(window.__GOT);
"""


def _grab(c, scale, sharpen=0.0):
    import base64
    import numpy as np
    d = json.loads(c.js(_GRAB % (scale, sharpen), timeout=90))
    a = np.frombuffer(base64.b64decode(d["r"]), np.uint8).astype(float)
    return a.reshape(d["h"], d["w"])


def _boxblur(a, k):
    """A control, not a filter: if plain blur scored well the metric below would be measuring
    softness rather than reconstruction, and could not arbitrate between two AA filters."""
    import numpy as np
    from numpy.lib.stride_tricks import sliding_window_view
    g = np.exp(-((np.arange(k) - k // 2) ** 2) / (2 * (k / 4.0) ** 2))
    g /= g.sum()
    w = sliding_window_view(np.pad(a, k // 2, mode="edge"), (k, k))
    return (w * np.outer(g, g)).sum(axis=(2, 3))


def bench_edges(c, url):
    """How far is the silhouette from a properly resolved one, and does the error have a
    direction to it?

    Ground truth is a 2.2x march resolved by the post pass to the SAME canvas size, so this is
    a like-for-like comparison of output pixels and not of buffers. Every arm comes from one
    page load behind TFREEZE: comparing across loads is void, because the pause lands at a
    different point in the track and the section, material and contrast all move with it.
    """
    import numpy as np
    load_track(c, url)
    pin(c)
    c.js(_GRAB_HOOK)
    ref = _grab(c, 2.20)
    gx = np.diff(ref, axis=1)[:-1, :]
    gy = np.diff(ref, axis=0)[:, :-1]
    band = (np.abs(gx) + np.abs(gy)) > 18.0
    ang = np.degrees(np.arctan2(np.abs(gx), np.abs(gy) + 1e-9))   # 0 = horizontal edge
    naxis = band & ((ang < 20) | (ang >= 70))
    diag = band & (ang >= 20) & (ang < 70)
    print("  silhouette band %.2f%% of box   near-axis %d px   diagonal %d px"
          % (100.0 * band.mean(), naxis.sum(), diag.sum()))

    def rmse(img, m):
        e = (img - ref)[:-1, :-1]
        return float(np.sqrt((e[m] ** 2).mean()))

    print("\n  rscale   all edges   near-axis   diagonal")
    for sc in (0.80, 0.92, 1.00, 1.10, 1.25):
        img = _grab(c, sc)
        print("   %.2f     %7.3f     %7.3f    %7.3f"
              % (sc, rmse(img, band), rmse(img, naxis), rmse(img, diag)))
    print("\n  The resolve switches from FXAA to a real 4-tap tent above ssRatio 1.05, which is")
    print("  why 1.00 -> 1.10 is a step and not a slope. See the governor's HEADROOM/SS_MIN.")

    raw = _grab(c, 1.00)
    print("\n  metric control -- blur is not reconstruction, so it must score WORSE:")
    for k in (3, 5, 7):
        print("    native + %dx%d gaussian   %7.3f" % (k, k, rmse(_boxblur(raw, k), band)))
    print("    native, unblurred        %7.3f" % rmse(raw, band))


# ------------------------------------------------------------------ frame cost
# WHY THIS EXISTS. Three cost claims in viewer.html were wrong at once, and each cost a long
# detour to disprove:
#   - the soft shadow was "about 4% of the frame". It is 42%. The ablation switch it was measured
#     through went via mix(1.0, calcSha(...), u_dxs.y), and mix evaluates both arguments, so it
#     marched the full shadow and multiplied it by zero.
#   - AO was assumed negligible on tap count -- four taps against the shadow's forty-eight. It
#     carries two thirds of the morph's extra cost, because calcSha's bounding-sphere returns are
#     taken for most shaded points and its loop rarely runs its budget.
#   - my own first two ablation passes produced fourteen identical rows, and then savings of the
#     WRONG SIGN.
# The last one is the method problem this arm fixes, and it has two halves.
#
# VSYNC HIDES EVERYTHING. At 60Hz every configuration reads 16.70ms whatever it is doing, so an
# ablation below the cap measures nothing at all. The frame has to be pushed well clear of it
# first, and if it cannot be, the honest output is a refusal rather than a table of zeroes.
#
# AND THE BASELINE DRIFTS. Measured across separate page loads the idle frame moved 98.0ms to
# 70.8ms on one machine; thermally, a run takes minutes and the machine is not the same at the
# end as at the start. So every ablation is paired with a baseline taken immediately before it
# and the two are differenced. Unpaired, this produced ablations that "cost" 3.4ms to switch OFF.
_COST_ABL = [
    ("post: bloom",          "DX.bloom=0;"),
    ("post: chroma",         "DX.chroma=0;"),
    ("post: sharpen",        "DX.sharpen=0;"),
    ("grain",                "GRAIN.amt=0;"),
    ("scene: AO",            "DXS.ao=0;"),
    ("scene: shadow",        "DXS.shadow=0;"),
    ("scene: fill light",    "DXS.fill=0;"),
    ("scene: translucency",  "DXS.trans=0;"),
    ("shadow taps to floor", "shaScale=0;"),
    ("ALL post",             "DX.bloom=0;DX.thr=0;DX.chroma=0;DX.sharpen=0;DX.mblur=0;GRAIN.amt=0;"),
    ("ALL scene extras",     "DXS.ao=0;DXS.shadow=0;DXS.fill=0;DXS.twoTone=0;DXS.trans=0;shaScale=0;"),
]
_COST_RESTORE = ("DX.bloom=1;DX.thr=1;DX.chroma=1;DX.sharpen=1;DX.mblur=1;GRAIN.amt=1;"
                 "DXS.ao=1;DXS.shadow=1;DXS.fill=1;DXS.twoTone=1;DXS.trans=1;shaScale=1;")


def _cost_bench(c, js, ms=3000):
    import numpy as np
    v = c.js("""
        %s
        await new Promise(r=>setTimeout(r,800));
        const t=[]; let last=performance.now(); const t0=last;
        await new Promise(res=>{ const h=()=>{ const n=performance.now(); t.push(n-last); last=n;
          if(n-t0<%d) requestAnimationFrame(h); else res(); }; requestAnimationFrame(h); });
        return JSON.stringify(t.slice(6));""" % (js, ms), timeout=90)
    return float(np.median(np.array(json.loads(v), float)))


def bench_costs(c, url):
    """What each pass costs, by paired ablation on a frame pushed clear of vsync."""
    import numpy as np
    c.js("""window.QLOCK=true; window.POSE={spin:1.0,cam:0.6,tumble:0.4,swirl:0.2};
            RENDER.pinScale=true; await new Promise(x=>setTimeout(x,1500)); return 1;""")
    rs = None
    for r in (1.0, 2.2, 3.4, 4.2, 5.0, 6.0):
        c.js("rscale=%f; applyScale(); await new Promise(x=>setTimeout(x,1000)); return 1;" % r)
        v = _cost_bench(c, "", 2000)
        print("    rscale %.1f -> %6.2f ms" % (r, v))
        rs = r
        if v > 45:
            break
    base = _cost_bench(c, _COST_RESTORE)
    if base < 25.0:
        print("\nREFUSING TO REPORT: the frame is %.2f ms, which is at or near the vsync cap."
              % base)
        print("  Every ablation would read the same number. Raise the render scale or measure on")
        print("  a slower machine -- a table of zeroes is worse than no table.")
        return
    print("\nbaseline %.2f ms at rscale %.1f. Each row pairs its OWN baseline, taken immediately"
          % (base, rs))
    print("  before it, so drift cancels rather than accumulating.\n")
    print("  ablation                  baseline    ablated     saved     share")
    for name, js in _COST_ABL:
        b = _cost_bench(c, _COST_RESTORE)
        a = _cost_bench(c, _COST_RESTORE + js)
        flag = "" if a <= b else "   <- negative: noise, not a saving"
        print("  %-22s   %6.2f     %6.2f    %+6.2f   %5.1f%%%s"
              % (name, b, a, a - b, 100 * (b - a) / b, flag))
    c.js(_COST_RESTORE + " return 1;")
    print("\nWhatever is left after the scene and post rows is the primary march, and the only")
    print("  lever on that is rscale -- see the shadow-lever note in viewer.html.")


# ------------------------------------------------------------------ the filter cell
# WHY. "Filter cell is still too much, it looks like a mess." The cell that reaches the shader
# is not the slider: it is the slider times dpr times dprScale times a contrast term times a
# music term, so any judgement about where the subject survives has to be made on the PRODUCT,
# in device pixels. FCELLPIN in viewer.html pins exactly that, so this sweeps the real quantity.
#
# THE METRIC IS SILHOUETTE RECOVERY, not similarity to the unfiltered frame. A halftone is
# supposed to look nothing like its source close up -- that is what a halftone is -- so scoring
# resemblance would condemn the filter at every setting. What the complaint is actually about is
# the SUBJECT disappearing: past some cell the dots stop describing a shape. So the reference is
# the unfiltered frame's foreground mask, and the score is how much of that mask you can still
# recover from the filtered frame after a FIXED 3px blur -- fixed, and deliberately not scaled
# with the cell, because a blur that grows with the cell would hand every setting the same score.
#
# AND THE REFERENCE IS _mask, WHICH IS A LUMA SPLIT. Read its docstring: it is not tracking the
# form, so "the subject covers 64% of the box" in this arm's output means the luma split, not the
# shape. This is the second reason nothing in the filter commit rests on these numbers.


def _mask(a):
    """A LUMA SPLIT, NOT A SUBJECT MASK, and the difference has cost real time twice.

    Otsu picks the threshold that best separates the histogram into two halves. On these frames
    the background is a lit gradient covering the whole plate, so the split it finds is usually
    inside the BACKGROUND, not between the form and everything else. Measured: on the filter
    arm's reference frame it called 64-65% of the box "subject", and asked for a bounding box it
    returns the whole canvas on every frame -- which is what it should return, for a mask that is
    not tracking the form.

    So it is fine for what it was written for -- comparing one filtered frame against another at
    the SAME pose, where whatever it selects it selects consistently -- and it is wrong for any
    question about where the form is or how big it is.

    USE window.DBGMASK FOR THAT, which is a real subject mask and which I previously recorded
    here as not being one. Wrong: the scene pass stores the ray's depth on a HIT and the
    sentinel 99 on a MISS -- the sentinel exists so a ray pointing away cannot report itself as
    the nearest possible hit -- so DBGMASK's `alpha < 17` means "hit the form" and renders it
    white. Read it as `pixel > 128`. Reading it the other way round selects the background and
    reports the form as 78-92% of the frame, which is what it did.
    """
    import numpy as np
    h, _ = np.histogram(a, bins=256, range=(0, 256))
    p = h / max(h.sum(), 1)
    om, cut = -1.0, 128
    w0 = 0.0
    m0 = 0.0
    mt = float((np.arange(256) * p).sum())
    for t in range(1, 255):
        w0 += p[t]
        m0 += t * p[t]
        w1 = 1.0 - w0
        if w0 < 1e-6 or w1 < 1e-6:
            continue
        v = (mt * w0 - m0) ** 2 / (w0 * w1)
        if v > om:
            om, cut = v, t
    return a > cut


def bench_filter(c, url):
    """Where does the subject stop surviving the filter, in device pixels?"""
    import numpy as np
    load_track(c, url)
    pin(c)
    c.js(_GRAB_HOOK)
    c.js("window.FCELLPIN=null; setCtl('selFilt','0'); return 1;")
    ref = _mask(_grab(c, 1.0))
    grow = _boxblur(ref.astype(float), 25)
    BAND = (grow > 0.02) & (grow < 0.98)      # a fixed collar around the true silhouette
    print("  reference subject covers %.1f%% of the box; the scored band is %.1f%% of it"
          % (100.0 * ref.mean(), 100.0 * BAND.mean()))

    names = {"1": "Halftone dots", "2": "Halftone lines", "3": "Pixelate", "6": "ASCII"}
    cells = [3, 4, 6, 8, 10, 12, 14, 16, 20, 24, 30, 40]
    out = {}
    for m, label in names.items():
        c.js("setCtl('selFilt','%s'); return 1;" % m)
        row = []
        for px in cells:
            c.js("window.FCELLPIN=%d; return 1;" % px)
            g = _boxblur(_grab(c, 1.0), 3)
            got = _mask(g)
            # SCORED IN A BAND AROUND THE SILHOUETTE, not over the whole box. The interior of a
            # halftoned form is dots either way and agrees with the reference by accident, which
            # swamped the first version of this: whole-box IoU fell from 0.81 to 0.56 across a
            # 13x range of cell with no knee anywhere, and ASCII scored HIGHER as it got coarser.
            # The damage the complaint is about is at the edge -- the outline stops describing a
            # shape -- so the score is IoU restricted to a fixed 12px band around the true edge.
            row.append(float((got & ref)[BAND].sum()) / max(float((got | ref)[BAND].sum()), 1.0))
        out[label] = row
        print("  %-15s " % label + " ".join("%5.2f" % v for v in row))
    print("  %-15s " % "cell (device px)" + " ".join("%5d" % v for v in cells))
    return out


# ------------------------------------------------------------------ resolution, fold controlled
# FOLD DUTY IS THE CONFOUND, and it took three wrong conclusions in one session to see it. How
# much of a run the kaleidoscope is open varies from 12% to 93% with the music, and it moves the
# share of frames above the resolve threshold by more than any governor change measured here.
# Two readings taken that way said a change did nothing and made oscillation three times worse;
# with the duty held equal the same change was better on every count.
#
# So this arm never measures the Director's fold. It pins the fold ON and OFF in turn and reports
# both, which is the only comparison that means anything across builds -- and the two together
# say more than the mixed number ever did: OFF is what the machine can hold, ON is what it holds
# when the most expensive thing in the renderer is running.
def bench_quality(c, url, secs=70):
    """Effective resolution with the fold pinned, which is the only way it compares across runs."""
    import numpy as np
    fails = []

    def check(name, ok, detail=""):
        print("  %-4s %s%s" % ("ok" if ok else "FAIL", name, ("   " + detail) if detail else ""))
        if not ok:
            fails.append(name)

    out = {}
    for tier in ("high", "ultra"):
        for fold in ("off", "on"):
            # A FRESH PAGE PER CONFIGURATION. The first version of this arm measured all four in
            # one load and every one of them inherited the previous governor's ssCeil, shaScale
            # and dprScale -- it reported Ultra at p05 0.70 and 36 reversals where a clean load
            # of the same build reads 0.88 and 12. The note at the top of this file says an old
            # tab is not a clean build; it is just as true of an old tier.
            _goto(c, "http://127.0.0.1:%d/" % PORT, settle=2.5)
            load_track(c, url)
            c.js("applyTier('%s'); setCtl('selKal','%s'); return 1;" % (tier, fold))
            d = json.loads(c.js("""
              const S=[]; let t0=performance.now(); const cv=document.querySelector('canvas');
              const tick=()=>{ S.push([performance.now()-t0, RW/Math.max(1,cv.width), rscale, kalAmt]);
                if(performance.now()-t0 < %d) requestAnimationFrame(tick); };
              requestAnimationFrame(tick);
              await new Promise(r=>setTimeout(r,%d));
              return JSON.stringify(S);""" % (secs * 1000, secs * 1000 + 2000), timeout=secs + 60))
            a = np.array(d, dtype=float)
            late = a[a[:, 0] > 15000]
            ss, rs, kal = late[:, 1], late[:, 2], late[:, 3]
            ch = np.where(np.abs(np.diff(rs)) > 1e-6)[0]
            st = np.sign(np.diff(rs)[ch])
            rev = int((np.diff(st) != 0).sum()) if len(st) > 1 else 0
            out[(tier, fold)] = (float(np.median(ss)), 100.0 * (ss > 1.05).mean(),
                                 float(np.percentile(rs, 5)), rev, 100.0 * (kal > 0.35).mean())
            print("  %-5s fold %-3s | ss p50 %.2f | above the tent %5.1f%% | rscale p05 %.2f | reversals %2d | duty %5.1f%%"
                  % (tier, fold, *out[(tier, fold)]))

    # With the fold OFF the machine is not being asked for anything unusual, so a tier that
    # cannot hold its own resolve threshold there has a problem that is not the music's fault.
    for tier in ("high", "ultra"):
        check("%s clears the resolve threshold with the fold off" % tier,
              out[(tier, "off")][1] >= 80.0, "%.1f%% of frames" % out[(tier, "off")][1])
    # NOT ASSERTED: that Ultra keeps the native floor its own note promises. It does not -- the
    # fold relaxes the floor by KFL and the march reaches 0.84 there, on both tiers. That was
    # written as an assertion first, failed, and the code was right: trading the shadow budget
    # for march pixels during a fold improves the number, it does not restore the promise. A
    # test that asserts something the code has never done is a test that is always red.
    # The 1Hz oscillator the banded branch warns about would be roughly one reversal per tick,
    # about 110 over this window. The bar is set where that is caught and ordinary adaptation is
    # not; the gap between the tiers is printed above rather than asserted, because it is a known
    # open difference and not a regression.
    for tier in ("high", "ultra"):
        check("%s does not hunt while folded" % tier, out[(tier, "on")][3] <= 45,
              "%d reversals in %ds" % (out[(tier, "on")][3], secs - 15))
    check("the march never goes below the fold-relaxed floor",
          min(out[(t, "on")][2] for t in ("high", "ultra")) >= 0.70 - 0.02,
          "worst rscale p05 %.2f against a floor of 0.70"
          % min(out[(t, "on")][2] for t in ("high", "ultra")))
    if fails:
        raise AssertionError("quality failures: " + ", ".join(fails))


# ------------------------------------------------------------------ the purchase pages
# WHY THIS EXISTS. The billing JS on the two site pages is real logic now -- it decides which
# packs are on sale through which channel, what a licence redemption says, and whether a key is
# stored -- and it had no coverage at all. It was verified three times by hand in one session,
# which is the definition of something that should be a test. The parts it guards are the parts
# where being wrong costs money or tells a paying customer something false.
#
# THREE SERVERS, BECAUSE THE INTERESTING CASES ARE ABOUT CONFIGURATION:
#   the stub          a real server with Gumroad configured and only _gumroad_verify replaced
#   the main server   already running, Gumroad not configured -- the default state
#   http.server       no /packs at all: the page served from a host that has never heard of it
# The third is the one the code comments claim to handle and the one nobody would think to try.
_SITE_STUB_PORT = int(os.environ.get("ATONAL_SITE_PORT", "8791"))
_SITE_STATIC_PORT = int(os.environ.get("ATONAL_SITE_STATIC_PORT", "8792"))


def _wait_for(url, timeout=25):
    end = time.time() + timeout
    while time.time() < end:
        try:
            urllib.request.urlopen(url, timeout=2).read()
            return True
        except Exception:
            time.sleep(0.3)
    return False


def _goto(c, url, settle=2.2):
    c.send("Page.navigate", {"url": url})
    time.sleep(settle)


def bench_site(c, url):
    """The purchase pages, in the three configurations that change what they may show."""
    fails = []      # subprocess, tempfile and shutil are already imported at module scope

    def check(name, ok, detail=""):
        print("  %-4s %s%s" % ("ok" if ok else "FAIL", name, ("   " + detail) if detail else ""))
        if not ok:
            fails.append(name)

    tmp = tempfile.mkdtemp(prefix="atonal-site-")
    stub = subprocess.Popen([sys.executable, os.path.join(ROOT, "tests", "site_stub.py"),
                             str(_SITE_STUB_PORT), os.path.join(tmp, "b.db")],
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    static = subprocess.Popen([sys.executable, "-m", "http.server", str(_SITE_STATIC_PORT),
                               "--bind", "127.0.0.1", "--directory", ROOT],
                              stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        S = "http://127.0.0.1:%d" % _SITE_STUB_PORT
        T = "http://127.0.0.1:%d" % _SITE_STATIC_PORT
        if not _wait_for(S + "/packs"):
            raise AssertionError("the site stub did not come up on %d" % _SITE_STUB_PORT)
        if not _wait_for(T + "/site/index.html"):
            raise AssertionError("the static host did not come up on %d" % _SITE_STATIC_PORT)

        # ---- 1. the landing page, Gumroad configured ----
        _goto(c, S + "/site/index.html")
        d = json.loads(c.js("""
          return JSON.stringify({
            gum:[...document.querySelectorAll('[data-gum]')].map(a=>({p:a.dataset.gum,
                 shown:a.style.display!=='none', href:a.getAttribute('href'), t:a.target})),
            prices:[...document.querySelectorAll('[data-price]')].map(e=>e.textContent.trim()),
            redeemLine: document.getElementById('redeemLine').style.display!=='none'});"""))
        shown = sorted(g["p"] for g in d["gum"] if g["shown"])
        check("landing offers only the packs Gumroad actually sells",
              shown == ["fifty", "ten"], "showed %s" % shown)
        check("and opens them in a new tab with rel=noopener",
              all(g["t"] == "_blank" for g in d["gum"] if g["shown"]))
        check("landing shows the redemption route", d["redeemLine"])
        # AUTHORED "6 EUR", NOT "6.00 EUR": the fetch is supposed to confirm the price, not
        # restyle it. This caught Intl's two-decimal default rewriting the design.
        check("whole prices stay whole", all(".00" not in p for p in d["prices"]),
              "%s" % d["prices"])

        # ---- 2. the landing page against a server with Gumroad off ----
        _goto(c, "http://127.0.0.1:%d/site/index.html" % PORT)
        d = json.loads(c.js("""
          return JSON.stringify({
            any:[...document.querySelectorAll('[data-gum]')].some(a=>a.style.display!=='none'),
            line: document.getElementById('redeemLine').style.display!=='none'});"""))
        check("with Gumroad unconfigured the landing page offers none of it",
              (not d["any"]) and (not d["line"]))

        # ---- 3. the landing page with no API at all ----
        _goto(c, T + "/site/index.html")
        d = json.loads(c.js("""
          return JSON.stringify({
            prices:[...document.querySelectorAll('[data-price]')].map(e=>e.textContent.trim()),
            any:[...document.querySelectorAll('[data-gum]')].some(a=>a.style.display!=='none'),
            ctas:[...document.querySelectorAll('[data-cta]')].map(a=>a.getAttribute('href')),
            prio: !!document.querySelector('[data-prio]')});"""))
        check("with no server the landing page keeps its authored markup",
              d["prices"] and all("\u20ac" in p for p in d["prices"]) and not d["any"]
              and all(h == "./pricing.html" for h in d["ctas"]) and d["prio"],
              "%s" % d)

        # ---- 4. redemption, on the pricing page, against the stub ----
        _goto(c, S + "/site/pricing.html")
        c.js("localStorage.removeItem('atonal.key'); return 1;")

        def redeem(lic):
            return json.loads(c.js("""
              document.getElementById('licIn').value=%s;
              document.getElementById('redeemBtn').click();
              await new Promise(r=>setTimeout(r,1400));
              return JSON.stringify({note:document.getElementById('status').textContent.trim(),
                                     stored:localStorage.getItem('atonal.key')});"""
                                   % json.dumps(lic), timeout=60))

        r = redeem("ATONAL-REFUNDED-0002")
        check("a refunded licence is refused and stores nothing",
              "refunded" in r["note"] and not r["stored"], r["note"][:60])
        r = redeem("ATONAL-TEST-LICENCE-0001")
        check("a good licence grants and the key is saved in the browser",
              "10 credits added" in r["note"] and (r["stored"] or "").startswith("atk_"),
              r["note"][:70])
        first = r["stored"]
        # THE ONE THAT WAS LYING. A second paste granted nothing -- correctly -- and said "10
        # credits added" beside a balance that had not moved.
        r = redeem("ATONAL-TEST-LICENCE-0001")
        check("a second paste says it was already redeemed, not that credits were added",
              "Already redeemed" in r["note"] and "added" not in r["note"].split(".")[0],
              r["note"][:70])
        check("and the balance did not move", r["stored"] == first)

        # ---- 5. the key field, which is the only way to enter a key by hand ----
        d = json.loads(c.js("""
          localStorage.removeItem('atonal.key');
          document.getElementById('haveIn').value='atk_not_a_real_key_at_all';
          document.getElementById('haveBtn').click();
          await new Promise(r=>setTimeout(r,1200));
          const bad={note:document.getElementById('status').textContent.trim(),
                     stored:localStorage.getItem('atonal.key')};
          document.getElementById('haveIn').value=%s;
          document.getElementById('haveBtn').click();
          await new Promise(r=>setTimeout(r,1200));
          return JSON.stringify({bad:bad,
            good:{note:document.getElementById('status').textContent.trim(),
                  stored:localStorage.getItem('atonal.key')}});""" % json.dumps(first),
                              timeout=60))
        check("a key that does not exist is refused and NOT stored",
              "not recognised" in d["bad"]["note"] and not d["bad"]["stored"],
              d["bad"]["note"][:60])
        check("a real key is checked, saved, and its balance reported",
              d["good"]["stored"] == first and "credit" in d["good"]["note"],
              d["good"]["note"][:60])
    finally:
        for p_ in (stub, static):
            try:
                p_.terminate()
                p_.wait(timeout=5)
            except Exception:
                pass
        shutil.rmtree(tmp, ignore_errors=True)
    if fails:
        raise AssertionError("site failures: " + ", ".join(fails))


# ------------------------------------------------------------------ the motion guarantees
# WHY THIS EXISTS. viewer.html states two guarantees about the drawn rotation, in a comment at
# SYNC.spinSwing: the bar swing returns to zero on every downbeat, and THE RATE NEVER GOES
# NEGATIVE. Both were uncovered. A change that bounded the spin axis to keep the plate facing the
# camera broke the second one outright -- the drawn rate went negative on 52.1% of frames and sat
# within 2 deg/s of a standstill on 21.8% -- and every one of the twelve director rules passed
# while it did, because they are about WHEN the form changes and not about how it moves. The user
# reported it twice before it was found.
#
# The thresholds below are set from measurement and not from aspiration: on the 176bpm upload the
# shipped build measures 0.0% negative, 0.0% stalled and 5.2% of frames with the face turned past
# 0.30, so the bars are set where a real regression is caught and ordinary variation is not.
_MOT_REC = """
  window.__M=[]; let t0=performance.now();
  const tick=()=>{ const s=window.SYNC||{};
    if(s.playing) window.__M.push([performance.now()-t0, s.spinOut||0, s.swirlOut||0,
                                   s.spinSwing||0, s.swingPhi||0, window.FACEDOT]);
    if(performance.now()-t0 < %d) requestAnimationFrame(tick); };
  requestAnimationFrame(tick);
  await new Promise(r=>setTimeout(r,%d));
  return JSON.stringify({m:window.__M, face:!!(window.FACE&&FACE.on)});
"""


def bench_motion(c, url, secs=60):
    """The guarantees viewer.html makes about how the form turns, asserted."""
    import numpy as np
    load_track(c, url)
    d = json.loads(c.js(_MOT_REC % (secs * 1000, secs * 1000 + 2500), timeout=secs + 90))
    a = np.array(d["m"], dtype=float)
    fails = []

    def check(name, ok, detail=""):
        print("  %-4s %s%s" % ("ok" if ok else "FAIL", name, ("   " + detail) if detail else ""))
        if not ok:
            fails.append(name)

    if len(a) < 200:
        raise AssertionError("motion: only %d frames; nothing can be asserted" % len(a))
    t = a[:, 0] / 1000.0
    # THE TURN IS THE SUM OF THE TWO IN-PLANE ANGLES, because which one carries it depends on
    # FACE: spin when the free three-axis motion is on, swirl when the plate is held face-on.
    # Asserting either alone passes vacuously in the other mode.
    turn = a[:, 1] + a[:, 2]
    dt = np.diff(t)
    rate = np.diff(turn) / np.maximum(dt, 1e-6) * 180.0 / np.pi
    rate = rate[np.abs(rate) < 2000]        # drop the frame either side of a seek or a stall
    print("  %d frames over %.0fs, FACE.on=%s | turn rate p05 %.1f p50 %.1f p95 %.1f deg/s"
          % (len(a), t[-1], d["face"], np.percentile(rate, 5), np.median(rate),
             np.percentile(rate, 95)))

    neg = float((rate < 0).mean())
    check("the drawn turn never reverses", neg <= 0.01,
          "negative on %.1f%% of frames" % (100 * neg))
    stall = float((np.abs(rate) < 2.0).mean())
    check("and never stalls", stall <= 0.02,
          "within 2 deg/s of a standstill on %.1f%% of frames" % (100 * stall))

    # "the swing returns to zero on every downbeat" -- swingPhi is the bar phase and is 0 there
    sw, phi = a[:, 3], a[:, 4]
    peak = float(np.percentile(np.abs(sw), 95))
    at_db = np.abs(sw)[(phi < 0.02) | (phi > 0.98)]
    if len(at_db) > 20 and peak > 1e-6:
        check("the bar swing is zero on the downbeat",
              float(at_db.mean()) <= 0.25 * peak,
              "mean |swing| there %.5f against a p95 of %.5f" % (at_db.mean(), peak))
    else:
        check("the bar swing is zero on the downbeat", True,
              "(no swing on this track: peak %.6f)" % peak)

    # and the face, which is the whole point of FACE.on
    fd = a[:, 5]
    fd = fd[np.isfinite(fd)]
    if d["face"] and len(fd) > 100:
        check("the face stays presented", float((fd < 0.30).mean()) <= 0.12,
              "|n.v| p50 %.2f, turned past 0.30 on %.1f%% of frames"
              % (np.median(fd), 100 * (fd < 0.30).mean()))
    else:
        check("the face stays presented", True, "(FACE.on is false; the bound is not in play)")

    if fails:
        raise AssertionError("motion guarantees failed: " + ", ".join(fails))


# ------------------------------------------------------------------ director rules
# WHY THESE ARE HERE. One session changed about ten of the Director's behaviours -- the ladder's
# order, the pacing, the phrase lock, the "a boundary is not a reason" gate, the fold's duty --
# and nothing covered any of them. tests/run.py never opens viewer.html, so every one of those
# rules could be undone by an edit and no suite would notice. These assert the rules that are
# cheap to check from a recording of real playback: WHEN a change is allowed to happen, not what
# it looks like.
#
# On the generated fixture, not a real upload: 128s of 8 sections at 120bpm, boundaries known by
# construction at 16s intervals, which is 8 bars -- so a section boundary is also a phrase
# boundary and the phrase rule is satisfiable rather than accidentally impossible.
_DIR_REC = """
  window.__L=[]; window.__PH=0; window.__D=[]; let lastShape=null;
  window.__A={n:0,held:0,open:0,shut:0,inMorph:0,kalIn:0,kalOut:0,pm:0,step:0,stepSecs:4,
              vocabFolded:99,vocabOpen:99};
  const rec=()=>{
    // EVERY DECISION, not every visible change. chooseMode writes __SHAPE on each call and
    // updates the energy the gate compares against -- including calls that return the shape
    // already showing and fire nothing. Testing consecutive CHANGES therefore skips over those
    // and measures a pair the rule was never applied to, which is what made this fail against
    // correct code.
    if(window.__SHAPE && window.__SHAPE!==lastShape){
      lastShape=window.__SHAPE;
      window.__D.push({t:pos(), e:window.__SHAPE.energy, held:!!window.__SHAPE.held});
    }
    // Aggregates accumulated IN PAGE rather than shipping every frame: a 126s run is ~7500
    // frames and only these summaries are wanted.
    {
      const A=window.__A;
      A.n++;
      if(kalHeld) A.held++;
      if(kalAmt>0.35) A.open++;
      if(kalAmt<0.02) A.shut++;
      if(phase===1){ A.inMorph++; A.kalIn+=kalAmt;
                     const st=mix-A.pm; if(st>0 && st>A.step){ A.step=st; A.stepSecs=morphSecs; } }
      else { A.kalOut+=kalAmt; }
      A.pm=mix;
      if(typeof allowedModes==='function'){
        const al=allowedModes().length;
        if(kalHeld && al<A.vocabFolded) A.vocabFolded=al;
        if(!kalHeld && al<A.vocabOpen) A.vocabOpen=al;
      }
    }
    if(phase===1 && window.__PH===0){
      const s=window.__SHAPE||{};
      window.__L.push({t:pos(), from:mode, to:mode2, e:s.energy,
                       bar:swBarK, anch:swPhAnchor, beats:morphBeats(),
                       secs:morphSecs, held:kalHeld?1:0});
    }
    window.__PH=phase;
    if(pos()<%f) requestAnimationFrame(rec);
  };
  requestAnimationFrame(rec);
  await new Promise(r=>setTimeout(r,%d));
  const db=(dbSet?Array.from(dbSet):[]);
  return JSON.stringify({ev:window.__L, dec:window.__D, agg:window.__A, db:db, grid:PHRASE_GRID,
    foldMin:FOLD_MIN, dtCap:MORPH_DT_CAP,
    minSecs:REFORM_MIN_SECS, minDE:REFORM_MIN_DE, idle:REFORM_IDLE_SECS,
    maxBars:(typeof REFORM_MAX_BARS==='number'?REFORM_MAX_BARS:-1), maxWait:REFORM_MAX_WAIT,
    pace:pace(), fast:MORPH_SECS.fast, slow:MORPH_SECS.slow,
    duty:KAL_DUTY, bpm:(director&&director.tempo&&director.tempo.bpm)||0});
"""


# ------------------------------------------------------------------ the exported file
# WHY THIS EXISTS. viewer.html contains a hand-written MP4 muxer -- box sizes, sample tables,
# chunk offsets, an esds descriptor -- and nothing had ever opened a file it produced. Every
# claim about the export path was an argument from the source rather than from a file.
#
# So this builds real files through the real muxer and READS THEM BACK: the box tree is parsed
# here in Python against the spec, and the audio is decoded out of the finished file by the
# browser and located by its onset. The muxer turned out to be correct, which is worth having
# pinned; the SYNC did not.
_MP4_CONTAINERS = {"moov", "trak", "mdia", "minf", "stbl", "dinf", "edts"}


def _mp4_walk(buf, start, end, path=(), out=None):
    """Every box as (path, offset, size). Raises on anything that does not parse."""
    import struct
    out = [] if out is None else out
    o = start
    while o < end:
        if end - o < 8:
            raise AssertionError("%d trailing bytes at %d are not a box" % (end - o, o))
        sz = struct.unpack(">I", buf[o:o + 4])[0]
        typ = buf[o + 4:o + 8].decode("latin1")
        if sz == 0:
            sz = end - o
        if sz < 8 or o + sz > end:
            raise AssertionError("box %r at %d claims %d bytes, %d remain"
                                 % (typ, o, sz, end - o))
        p = path + (typ,)
        out.append((p, o, sz))
        if typ in _MP4_CONTAINERS:
            _mp4_walk(buf, o + 8, o + sz, p, out)
        elif typ == "stsd":                       # full box, then a count, then sample entries
            _mp4_walk(buf, o + 16, o + sz, p, out)
        elif typ == "avc1":                       # 78 bytes of visual fields, then child boxes
            _mp4_walk(buf, o + 8 + 78, o + sz, p, out)
        elif typ == "mp4a":                       # 28 bytes of audio fields, then child boxes
            _mp4_walk(buf, o + 8 + 28, o + sz, p, out)
        o += sz
    return out


def _u32(b, o):
    import struct
    return struct.unpack(">I", b[o:o + 4])[0]


def _mp4_build_js(nv, na, extra=""):
    return """
      const mk=(n,base,keyEvery)=>{const a=[];for(let i=0;i<n;i++){
        const b=new Uint8Array(4+(i%%7));b.fill(base+(i&15));
        a.push({bytes:b,key:keyEvery?(i%%keyEvery===0):false});}return a;};
      const desc=new Uint8Array([1,0x42,0xE0,0x1E,0xFF,0xE1,0,4,0x67,0x42,0xE0,0x1E,
                                 1,0,4,0x68,0xCE,0x3C,0x80]);
      const asc=new Uint8Array([0x11,0x90]);
      %s
      const blob=MP4.build(mk(%d,0xA0,6), desc, 1080,1920,60,
        %s);
      const buf=new Uint8Array(await blob.arrayBuffer());
      let s=''; for(let i=0;i<buf.length;i++) s+=String.fromCharCode(buf[i]);
      return JSON.stringify({b:btoa(s),type:blob.type});""" % (
        extra, nv,
        ("{samples:mk(%d,0x50,0), asc:asc, sampleRate:48000, channels:2}" % na) if na else "null")


# A 1kHz burst written at a known sample of the source, encoded, muxed, then DECODED BACK OUT
# of the finished file and located by its onset. This is the only check here that exercises the
# whole audio path at once, and it is the one that found the 44ms offset: everything upstream --
# chunk counts, sample tables, durations -- was already correct while the audio was still late.
_SYNC_JS = r"""
  const sr=48000, ch=2, N=1024, M=140, BURST=48000;
  const cfg={codec:'mp4a.40.2', sampleRate:sr, numberOfChannels:ch, bitrate:192000};
  try{ const s=await AudioEncoder.isConfigSupported(cfg);
       if(!s||!s.supported) return JSON.stringify({err:'AAC not supported in this browser'}); }
  catch(e){ return JSON.stringify({err:'AAC unavailable: '+e.message}); }
  const src=new Float32Array(M*N);
  for(let i=0;i<M*N;i++){ const d=i-BURST;
    src[i]=(d>=0&&d<2400)?Math.sin(2*Math.PI*1000*d/sr)*Math.exp(-d/600):0; }
  const samples=[]; let asc=null;
  const enc=new AudioEncoder({
    output:(chunk,md)=>{ if(md&&md.decoderConfig&&md.decoderConfig.description&&!asc)
                           asc=new Uint8Array(md.decoderConfig.description);
                         const b=new Uint8Array(chunk.byteLength); chunk.copyTo(b);
                         samples.push({bytes:b,key:true}); },
    error:e=>{}});
  enc.configure(cfg);
  for(let k=0;k<M;k++){
    const data=new Float32Array(N*ch);
    for(let i=0;i<N;i++){ data[i*ch]=src[k*N+i]; data[i*ch+1]=src[k*N+i]; }
    enc.encode(new AudioData({format:'f32',sampleRate:sr,numberOfFrames:N,
      numberOfChannels:ch,timestamp:Math.round(k*N/sr*1e6),data}));
  }
  await enc.flush(); enc.close();
  if(!samples.length||!asc) return JSON.stringify({err:'the encoder produced nothing'});
  const vdesc=new Uint8Array([1,0x42,0xE0,0x1E,0xFF,0xE1,0,4,0x67,0x42,0xE0,0x1E,
                              1,0,4,0x68,0xCE,0x3C,0x80]);
  const vs=[]; for(let i=0;i<180;i++){ const b=new Uint8Array(8); b.fill(1);
                                       vs.push({bytes:b,key:i===0}); }
  const blob=MP4.build(vs, vdesc, 320,240,60, {samples,asc,sampleRate:sr,channels:ch});
  const ab=await blob.arrayBuffer();
  const actx=new (window.OfflineAudioContext||window.webkitOfflineAudioContext)(1,sr,sr);
  let dec;
  try{ dec=await actx.decodeAudioData(ab.slice(0)); }
  catch(e){ return JSON.stringify({err:'the browser could not decode the muxed file: '+e.message}); }
  const d0=dec.getChannelData(0);
  let peak=0; for(let i=0;i<d0.length;i++){ const a=Math.abs(d0[i]); if(a>peak) peak=a; }
  let onset=-1; for(let i=0;i<d0.length;i++){ if(Math.abs(d0[i])>peak*0.1){ onset=i; break; } }
  return JSON.stringify({burstAt:BURST, onsetAt:onset, offsetSamples:onset-BURST,
                         offsetMs:(onset-BURST)/sr*1000, decLen:d0.length});
"""


def bench_export(c, url):
    """The MP4 the export path writes, parsed and decoded rather than argued about."""
    import base64
    import numpy as np
    fails = []

    def check(name, ok, detail=""):
        print("  %-4s %s%s" % ("ok" if ok else "FAIL", name, ("   " + detail) if detail else ""))
        if not ok:
            fails.append(name)

    NV, NA = 24, 17
    d = json.loads(c.js(_mp4_build_js(NV, NA), timeout=120))
    buf = base64.b64decode(d["b"])
    vsz = [4 + (i % 7) for i in range(NV)]
    asz = [4 + (i % 7) for i in range(NA)]

    try:
        boxes = _mp4_walk(buf, 0, len(buf))
        structural = ""
    except AssertionError as e:
        boxes, structural = [], str(e)
    check("the box tree parses to exactly the file length", not structural, structural)
    if structural:
        raise AssertionError("export: the file does not parse; nothing further is meaningful")

    top = [b for b in boxes if len(b[0]) == 1]
    check("ftyp, mdat, moov, in that order, covering the file",
          [b[0][0] for b in top] == ["ftyp", "mdat", "moov"]
          and sum(b[2] for b in top) == len(buf),
          "%s, %d bytes" % ([b[0][0] for b in top], len(buf)))

    def one(t, within=None):
        m = [b for b in boxes if b[0][-1] == t
             and (within is None or (within[1] < b[1] < within[1] + within[2]))]
        return m[0] if m else None

    def payload(box):
        return buf[box[1] + 12:box[1] + box[2]]        # past header and version/flags

    mvhd = payload(one("mvhd"))
    mvts, mvdur = _u32(mvhd, 8), _u32(mvhd, 12)
    traks = [b for b in boxes if b[0][-1] == "trak"]
    check("both tracks are present", len(traks) == 2, "%d traks" % len(traks))

    mdat = one("mdat")
    for tk in traks:
        mdhd, hdlr = payload(one("mdhd", tk)), payload(one("hdlr", tk))
        kind = hdlr[4:8].decode("latin1")
        mts, mdur = _u32(mdhd, 8), _u32(mdhd, 12)
        tkhd = payload(one("tkhd", tk))
        tdur = _u32(tkhd, 16)
        stts = payload(one("stts", tk))
        total = sum(_u32(stts, 4 + 8 * j) * _u32(stts, 8 + 8 * j) for j in range(_u32(stts, 0)))
        stsz = payload(one("stsz", tk))
        sizes = [_u32(stsz, 8 + 4 * j) for j in range(_u32(stsz, 4))]
        off = _u32(payload(one("stco", tk)), 4)
        want = vsz if kind == "vide" else asz

        check("%s sample table matches what was handed in" % kind, sizes == want,
              "%d entries, %d bytes" % (len(sizes), sum(sizes)))
        check("%s stts total == mdhd duration" % kind, total == mdur,
              "%d vs %d" % (total, mdur))
        check("%s track duration agrees with the movie timescale" % kind,
              tdur == round(mdur / mts * mvts), "%d vs %d" % (tdur, round(mdur / mts * mvts)))
        check("%s data sits inside mdat" % kind,
              mdat[1] + 8 <= off and off + sum(sizes) <= mdat[1] + mdat[2],
              "[%d,%d) in [%d,%d)" % (off, off + sum(sizes), mdat[1] + 8, mdat[1] + mdat[2]))
        # THE STRONGEST CHECK HERE: the bytes a player would read at the offsets the table gives
        # are the bytes that went in. A wrong offset or a wrong size passes every check above.
        exp = b"".join(bytes([(0xA0 if kind == "vide" else 0x50) + (i & 15)]) * want[i]
                       for i in range(len(want)))
        check("%s samples round-trip byte for byte" % kind, buf[off:off + sum(sizes)] == exp)
        check("%s hdlr name is null-terminated" % kind, hdlr[20:].endswith(b"\x00"),
              repr(bytes(hdlr[20:])))
        if kind == "vide":
            stss = payload(one("stss", tk))
            keys = [_u32(stss, 4 + 4 * j) for j in range(_u32(stss, 0))]
            check("the video track has sync samples", len(keys) > 0 and all(1 <= k <= NV
                  for k in keys), "%d of %d frames" % (len(keys), NV))

    # esds is what makes the audio track decodable at all; an inconsistent descriptor chain is
    # silent -- the file plays with no sound rather than failing to open.
    esds = one("esds")
    check("esds is present inside mp4a", esds is not None and "mp4a" in esds[0])
    if esds:
        p = payload(esds)
        tag, o = p[0], 1
        n = 0
        for _ in range(4):
            cbyte = p[o]; o += 1; n = (n << 7) | (cbyte & 0x7F)
            if not (cbyte & 0x80):
                break
        check("the ES descriptor length matches its box", tag == 0x03 and o + n == len(p),
              "tag 0x%02X, length %d, ends at %d of %d" % (tag, n, o + n, len(p)))

    # ---- the edit list, and the thing it exists for
    elst = one("elst")
    check("the audio track carries an edit list", elst is not None)
    if elst:
        p = payload(elst)
        check("it skips the AAC encoder delay", _u32(p, 8) == 2112,
              "media_time %d samples (%.1fms at 48k)" % (_u32(p, 8), _u32(p, 8) / 48.0))

    print("  --   decoding the finished file back to find where the audio actually landed")
    r = json.loads(c.js(_SYNC_JS, timeout=180))
    if r.get("err"):
        check("audio lands where it was written", False, r["err"])
    else:
        # A 1kHz burst written at sample 48000 of the source, muxed, then decoded out of the
        # finished file. Without the edit list this came back at 50113 -- 2113 samples, 44.0ms.
        check("audio lands where it was written", abs(r["offsetSamples"]) <= 64,
              "burst at %d, decoded at %d, %+d samples (%+.2fms); was +2113 (+44.0ms)"
              % (r["burstAt"], r["onsetAt"], r["offsetSamples"], r["offsetMs"]))

    # ---- and the sample tables have to survive a long take
    lim = json.loads(c.js("""
        const out={};
        for(const n of [1000, 200000]){
          try{ out[n]=(MP4.u32a(new Array(n).fill(7)).length===4*n)?'ok':'wrong length'; }
          catch(e){ out[n]=e.constructor.name; }
        }
        return JSON.stringify(out);""", timeout=90))
    check("a long take's sample table can be built", all(v == "ok" for v in lim.values()),
          "%s  (u32(...spread) threw RangeError between 100k and 125k)" % lim)

    if fails:
        raise AssertionError("export: " + ", ".join(fails))


# ------------------------------------------------------------------ shape and reflection
def bench_shape(c, url):
    """Two things that have to be CONTINUOUS, and were not.

    Neither is a look: both are quantities that move on their own while a track plays, and the
    code treated them as if they stood still. The form's scale rides the section energy and the
    motion patch; the material's roughness is eased toward a target every frame and the Print and
    Poster rolls change material by themselves. So an AO kernel fixed in world units, and a
    reflection path chosen by a hard threshold on roughness, both turn a smooth sweep into a
    visible step. These assert that neither does.
    """
    import numpy as np
    fails = []

    def check(name, ok, detail=""):
        print("  %-4s %s%s" % ("ok" if ok else "FAIL", name, ("   " + detail) if detail else ""))
        if not ok:
            fails.append(name)

    load_track(c, url)
    pin(c)
    c.js(_GRAB_HOOK)

    # ---- AO is a fraction of the form, so its contribution cannot depend on the form's size
    scales = (0.50, 0.65, 0.80, 1.00, 1.20, 1.45, 1.60)
    got, cover = [], []
    for s in scales:
        c.js("window.FSCALE=%f; return 1;" % s)
        on = _grab(c, 1.00)
        c.js("DXS.ao=0; return 1;")
        off = _grab(c, 1.00)
        c.js("DXS.ao=1; return 1;")
        c.js("window.DBGMASK=1; return 1;")
        m = _grab(c, 1.00) > 128
        c.js("window.DBGMASK=0; return 1;")
        cover.append(float(m.mean()))
        d = np.abs(on - off)
        got.append(float(d[m].mean()) if m.sum() > 500 else float(d.mean()))
    c.js("window.FSCALE=0; return 1;")
    # DID THE PIN DO ANYTHING? Run against a build without u_fsPin, window.FSCALE is just a
    # property nobody reads: every row then measures the identical frame, the spread comes out at
    # 0% and the check passes while having measured NOTHING. That is worse than no check, and it
    # is what this arm did the first time it was pointed at the old build. The form's share of the
    # box runs about 10% to 66% across this sweep, so if it does not move, the pin is not landing.
    if max(cover) - min(cover) < 0.10:
        raise AssertionError(
            "window.FSCALE did not change the form's size (subject %.1f%%-%.1f%% of the box). "
            "The pin is missing or ignored, so the AO sweep below would measure one frame seven "
            "times." % (100 * min(cover), 100 * max(cover)))
    print("  AO contribution by form scale: " +
          "  ".join("%.2f:%.1f" % (s, v) for s, v in zip(scales, got)))
    spread = (max(got) - min(got)) / max(1e-6, float(np.mean(got)))
    # Fixed radii measured 18.49 down to 10.70 and back to 12.46 across this range -- a 73%
    # spread. Scaled, 10.92 to 12.76, 17%. The bar is set between the two: the subject also grows
    # from 10% to 66% of the box over this sweep, so the population being averaged is not the
    # same at both ends and exact invariance is not on offer.
    check("AO does not change strength with the form's size", spread <= 0.35,
          "spread %.0f%% of the mean, against 73%% with the kernel fixed in world units"
          % (100 * spread))

    # ---- and the traced reflection fades in rather than switching on
    c.js("""for(const o of [MAT,MATT]){o.metal=1.0;o.reflect=1.0;o.rough=0.30;}
            FIN.rghMix=0;FINT.rghMix=0;window.WEAR.amt=0; return 1;""")
    xs = [0.48, 0.50, 0.52, 0.54, 0.56, 0.58, 0.60]
    imgs = {}
    for x in xs:
        c.js("MAT.rough=%f; MATT.rough=%f; return 1;" % (x, x))
        imgs[x] = _grab(c, 1.00)
    steps = {}
    for a, b in zip(xs, xs[1:]):
        d = np.abs(imgs[b] - imgs[a])
        steps[(a, b)] = (float(d.mean()), float((d > 8).mean()))
    print("  consecutive 0.02 roughness steps, mean |d| / share moving >8 levels:")
    for (a, b), (mn, sh) in steps.items():
        print("    %.2f -> %.2f   %6.3f   %6.3f%%" % (a, b, mn, 100 * sh))
    at = steps[(0.54, 0.56)]
    others = [v for k, v in steps.items() if k != (0.54, 0.56)]
    ref = float(np.median([o[0] for o in others]))
    # The gate sat at rgh 0.55. Before: 3.124 mean against a 0.75 median elsewhere, and 10.3% of
    # the frame moving more than 8 levels against 0.03% either side. MAT and MATT are both pinned
    # because MAT is eased toward MATT every frame -- setting only one of them measures the decay
    # back to the old value, which cost a whole wrong reading here.
    check("the traced reflection has no step at the roughness gate", at[0] <= 2.0 * ref,
          "the 0.54-0.56 step is %.3f against a %.3f median elsewhere (was 3.124 vs 0.75)"
          % (at[0], ref))
    check("and no part of the frame jumps across it", at[1] <= 0.01,
          "%.3f%% of pixels move more than 8 levels (was 10.31%%)" % (100 * at[1]))

    if fails:
        raise AssertionError("shape/reflection continuity failed: " + ", ".join(fails))


def bench_director(c, url):
    """The Director's timing rules, asserted against real playback."""
    import numpy as np
    load_track(c, url)
    # 126s covers the fixture, which is 128s long. A real track is longer, and the things
    # worth watching for are not all in its first two minutes -- the irregular bars that
    # broke the wait budget sit at 135s and 200s of the 176bpm upload. ATONAL_BENCH_SECS
    # opens the window; the run costs about that much wall clock, so it is not the default.
    secs = float(os.environ.get("ATONAL_BENCH_SECS", "126"))
    d = json.loads(c.js(_DIR_REC % (secs, int(secs * 1000) + 4000), timeout=secs + 90))
    ev, db = d["ev"], np.array(sorted(d["db"]))
    bpm, grid = d["bpm"], d["grid"]
    beat = 60.0 / max(bpm, 1e-6)
    fails = []

    def check(name, ok, detail=""):
        print("  %-4s %s%s" % ("ok" if ok else "FAIL", name, ("   " + detail) if detail else ""))
        if not ok:
            fails.append(name)

    print("  %d shape changes in %.0fs at %.1f bpm, phrase grid %d bars"
          % (len(ev), secs, bpm, grid))
    if len(ev) < 2:
        check("enough changes to judge", False, "got %d; the rules cannot be tested" % len(ev))
        raise AssertionError("director: too few changes to assert anything")

    # 1. every change lands on a real downbeat
    if len(db):
        off = [float(np.min(np.abs(db - e["t"]))) for e in ev]
        check("changes land on a downbeat", max(off) < beat * 0.5,
              "worst %.3fs against a %.3fs beat" % (max(off), beat))
    else:
        check("downbeat grid present", False)

    # 2. and on a phrase boundary. The wait budget is allowed to release one that has waited
    #    it out, so this asserts the RULE holds for the great majority rather than every one.
    pb = [((e["bar"] - e["anch"]) % grid + grid) % grid for e in ev]
    onp = sum(1 for x in pb if x == 0)
    check("changes land on a phrase boundary", onp >= max(1, int(0.8 * len(pb))),
          "%d of %d on bar 0 of the %d-bar grid" % (onp, len(pb), grid))

    # 3. no transition runs faster than the range that exists to bound it
    short = [e for e in ev if e["secs"] < d["fast"] - 1e-6]
    check("transition is never shorter than MORPH_SECS.fast", not short,
          "fastest %.2fs against a floor of %.2fs" % (min(e["secs"] for e in ev), d["fast"]))

    # 4. the spacing floor, halved at a section boundary, which is documented and deliberate
    gaps = np.diff([e["t"] for e in ev])
    floor = d["minSecs"] * d["pace"] * 0.5
    check("spacing respects the floor", len(gaps) == 0 or gaps.min() >= floor - 0.05,
          "tightest %.1fs against %.1fs (half of %.1f x pace %.2f)"
          % (gaps.min() if len(gaps) else 0, floor, d["minSecs"], d["pace"]))

    # 5. every DECISION answered a move in the music, unless the idle lapse let it through.
    #    Decisions, not visible changes: the gate compares against the energy of the last call
    #    to chooseMode, and a call that returns the shape already showing fires nothing but
    #    still moves that reference.
    dec = d.get("dec") or []
    bad = 0
    for i in range(1, len(dec)):
        dE = abs(dec[i]["e"] - dec[i - 1]["e"])
        if dE < d["minDE"] and (dec[i]["t"] - dec[i - 1]["t"]) < d["idle"]:
            bad += 1
    check("every decision had a musical reason", bad == 0,
          "%d of %d under dE %.3f without the idle lapse" % (bad, max(len(dec) - 1, 0), d["minDE"]))

    # 6. the fold is an accent, not the resting state -- BUT ONLY WHERE THERE ARE ENOUGH
    #    CHANGES TO SAY SO. This read `held <= 0.9` over however many changes a run happened to
    #    produce, which on a 126s window is three. Three Bernoulli samples against a duty of
    #    0.38 land all-folded by chance often enough that the same unchanged code gave 33% and
    #    then 100% on consecutive runs: a red that means nothing. Rule 7 below measures the same
    #    duty over every frame -- 7143 of them -- and is the assertion to trust. This one only
    #    adds whether the fold is open at CHANGES specifically, which needs n where d**n is
    #    rarer than the failure is worth: at 0.38 that is 8.
    held = float(np.mean([e["held"] for e in ev])) if ev else 0.0
    if len(ev) >= 8:
        check("fold is not pinned open at every change", held <= 0.9,
              "open at %.0f%% of %d changes, duty target %.2f" % (100 * held, len(ev), d["duty"]))
    else:
        check("fold is not pinned open at every change", True,
              "(only %d changes: %.0f%% open, too few to tell from chance -- see rule 7)"
              % (len(ev), 100 * held))

    # ---- the fold and the morph, which this session also changed and nothing covered ----
    A = d.get("agg") or {}
    n = max(A.get("n", 0), 1)
    print("  fold and transition, over %d frames" % n)

    # 7. the fold is an accent. The duty is a target the energy threshold is calibrated to, so
    #    this is a wide band -- it is checking that the mechanism works, not that a track hits
    #    a number. Before 2fa6da9 this read 66% against a 22% target.
    held = A.get("held", 0) / n
    check("fold duty is near its target", held <= d["duty"] * 2.0 + 0.05,
          "held %.0f%% against a target of %.0f%%" % (100 * held, 100 * d["duty"]))

    # 8. and it actually shuts. It never did: measured at 0.0% before the deadband fix, because
    #    an exponential approach to zero plus a deadband strands it just above.
    check("fold reaches fully closed", A.get("shut", 0) / n > 0.05,
          "%.0f%% of frames under kalAmt 0.02" % (100 * A.get("shut", 0) / n))

    # 9. and it gets out of the way of a shape change (efc33f8)
    if A.get("inMorph", 0) > 30 and (n - A.get("inMorph", 0)) > 30:
        kin = A.get("kalIn", 0) / A["inMorph"]
        kout = A.get("kalOut", 0) / (n - A["inMorph"])
        check("fold ducks during a transition", kin <= kout + 0.02,
              "mean kalAmt %.3f inside against %.3f outside" % (kin, kout))
    else:
        check("fold ducks during a transition", True, "(too few morph frames to judge)")

    # 10. a stall may not become a jump (4c90428). The cap is on dt, so the bound on one
    #     frame's mix step is MORPH_DT_CAP / that transition's length, plus a little slack for
    #     the frame the cap itself lands on.
    if A.get("step", 0) > 0:
        bound = d["dtCap"] / max(A.get("stepSecs", 4.0), 0.2)
        check("no single frame jumps the transition", A["step"] <= bound * 1.15,
              "worst step %.5f against a bound of %.5f" % (A["step"], bound))
    else:
        check("no single frame jumps the transition", True, "(no transition observed)")

    # 11. the vocabulary never collapses below the floor a folded passage is guaranteed
    vf = A.get("vocabFolded", 99)
    if vf < 99:
        check("folded vocabulary respects FOLD_MIN", vf >= d["foldMin"],
              "smallest allowed set while folded was %d, floor %d" % (vf, d["foldMin"]))
    else:
        check("folded vocabulary respects FOLD_MIN", True, "(fold never held)")

    # 12. the wait budget is counted in DOWNBEATS. This one is a structural check, not a
    #     behavioural one, and it is here because the behavioural version does not work: the
    #     bug it guards against shows up on 2 arrivals in 714 of the 176bpm upload, so a run
    #     that watches five changes would catch a revert about 1.4% of the time. Measured over
    #     every beat of all four analyses on hand, simulating both rules against the real beat
    #     grids: off-grid landings 2/714 and 2/751 under a beat budget, 0 under a bar count,
    #     for 2 extra beats of worst-case wait. A beat budget cannot be made correct -- a
    #     phrase's length in beats is not known until it is over -- so the assertion is on the
    #     shape of the rule rather than on an outcome it only rarely changes.
    check("the wait budget is counted in bars, not beats",
          d.get("maxBars") == grid and d.get("maxWait") >= grid * 11,
          "escape at %s bars, strand guard at %s beats" % (d.get("maxBars"), d.get("maxWait")))

    if fails:
        raise AssertionError("director rules failed: " + ", ".join(fails))


def main():
    what = (sys.argv[1] if len(sys.argv) > 1 else "all").lower()
    try:
        urllib.request.urlopen("http://127.0.0.1:%d/health" % PORT, timeout=3).read()
    except Exception:
        print("no server on %d -- start it with:  python server.py" % PORT)
        return 2
    if not os.path.exists(CHROME):
        print("Chrome not found at %s (set ATONAL_CHROME)" % CHROME)
        return 2
    # A REAL TRACK WHEN ONE IS OFFERED. The generated fixture is right for the structural arms
    # -- its bar grid and section boundaries are known by construction, and its downbeat grid is
    # OFFSET from its sections, which is exactly the property that caught the phrase lock only
    # covering one of two call sites. But fixtures do lie about material: this one peaks mid-bar
    # where real music peaks on the beat, so a rule that holds here is not yet known to hold.
    # ATONAL_BENCH_TRACK points any arm at a file in assets/ instead; a track already in the
    # analysis cache costs nothing to re-run.
    #     ATONAL_BENCH_TRACK=/assets/mine.mp3 python tests/render_bench.py director
    real = os.environ.get("ATONAL_BENCH_TRACK", "").strip()
    if real:
        url, truth, bpm = real, None, 0
        print("track: %s  (given by ATONAL_BENCH_TRACK, not the fixture)" % url)
    else:
        url, truth, bpm = serve_fixture()
        print("fixture: %s  (%.0f bpm, boundaries %s)" % (url, bpm, truth))
    rc = 0
    for name, fn, q in (("clock", bench_clock, ""), ("morph", bench_morph, "?readback"),
                        ("edges", bench_edges, ""), ("costs", bench_costs, ""),
                        ("filter", bench_filter, "?readback"),
                        ("motion", bench_motion, ""),
                        ("quality", bench_quality, ""),
                        ("site", bench_site, ""),
                        ("shape", bench_shape, ""),
                        ("export", bench_export, ""),
                        ("director", bench_director, "")):
        if what not in ("all", name):
            continue
        print("\n== %s ==" % name)
        c = open_viewer(q)
        try:
            fn(c, url)
        except Exception as e:
            print("  FAILED: %s" % str(e)[:400])
            rc = 1
        finally:
            c.close()
    return rc


if __name__ == "__main__":
    sys.exit(main())
